image: fedora:latest

variables:
  DEPS_COMMON: git libtool make redhat-rpm-config
               meson ninja-build gtk-doc glib2-devel
               gettext gettext-devel bzip2 rpmlint rpm-build

before_script:
- dnf install -y $DEPS_COMMON

fedora:
  script:
    - meson --buildtype=release build-default
    - ninja -C build-default
    - ninja -C build-default dist
    - rpmlint -o "NetworkEnabled False" build-default/spice-protocol.spec
    - mkdir -p ~/rpmbuild/SOURCES && cp build-default/meson-dist/spice-protocol*.tar.xz ~/rpmbuild/SOURCES/
    - rpmbuild -ba build-default/spice-protocol.spec
