image: fedora:latest

variables:
  DEPS_COMMON: git libtool make redhat-rpm-config
               meson ninja-build gtk-doc glib2-devel
               gettext gettext-devel bzip2 rpmlint rpm-build

before_script:
- dnf install -y $DEPS_COMMON

fedora-autotools:
  script:
    # Run with default options
    - ./autogen.sh
    - make
    - make distcheck
    - rpmlint -o "NetworkEnabled False" spice-protocol.spec
    - rpmbuild -ta spice-protocol-*.tar.bz2

fedora-meson:
  script:
    - meson --buildtype=release build-default
    - ninja -C build-default
    - ninja -C build-default dist
